# Generated by Django 3.1.3 on 2021-01-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookshop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookShop',
            new_name='Books',
        ),
    ]
